/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/latest-updates-publisher/wrangler.jsonc --env=staging --include-runtime=false workers/latest-updates-publisher/worker-configuration.d.ts` (hash: 02c0e0a0f368f647a22f2f691f76678d)
interface __BaseEnv_Env {
	DRAFTS: R2Bucket;
	DB: D1Database;
	JOBS: Queue;
	ASSETS: Fetcher;
	ENVIRONMENT: "staging";
	PUBLISHING_PAUSED: "true";
	DELIVERY_PAUSED: "true";
	SITES_JSON: "[]";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLISHING_PAUSED" | "DELIVERY_PAUSED" | "SITES_JSON">> {}
}
declare module "*.css" {
	const value: string;
	export default value;
}